title: My github pages
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.

#Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

#repo_url: 'https://github.com/rakshitha-mayya/my_gitpage-'
#edit_on_github: true
sticky_navigation: true
search_enabled: true